services:
  # 🧠 Backend - NestJS
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - app-network
    environment:
      - DATABASE_URL=${DATABASE_URL}

  # 💻 Frontend - Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Used inside Next.js to call the backend
      NEXT_PUBLIC_API_URL: http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network

# 🔗 Shared network for service communication
networks:
  app-network:
    driver: bridge


