services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: nmk
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - redisdata:/data
    command: [ 'redis-server', '--appendonly', 'yes' ]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - app-network
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: redis
    depends_on:
      - redis
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      BACKEND_API_BASE_URL: http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  redisdata:
  pgdata:

networks:
  app-network:
    driver: bridge


